// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzwkzjnvaxyntzjfgkdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6d2t6am52YXh5bnR6amZna2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjkzNzYsImV4cCI6MjA3NDAwNTM3Nn0.DCZhtRXvbzEn-JHB-n_qqS-iKaTRfw_LWaN2NLdFTMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});